### ISSUE TITLE
`x_type` can't be `None`

### ISSUE THREAD

**Issue by rcannood** [data-intuitive/dummy-anndata#7]
https://github.com/data-intuitive/dummy-anndata/blob/1aebde0c5ccdc5a1e99907f272c735199321ff3e/src/dummy_anndata/generate_dataset.py#L11-L24

Strictly speaking an AnnData doesn't need an X. However, setting `x_type` to `None` results in:

```
  AssertionError: Unknown matrix type: None
```

**Comment by LouiseDck** [comment]
See #9
