### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by rcannood** [data-intuitive/dummy-anndata#8]
### Description of feature

https://github.com/data-intuitive/dummy-anndata/blob/1aebde0c5ccdc5a1e99907f272c735199321ff3e/src/dummy_anndata/generate_dataset.py#L11-L24

Could type annotations be added to the inputs / outputs of each exposed function?

**Comment by LouiseDck** [comment]
Yes. I'm not sure it improves the legibility in every case though.
See #10
